From 3f3d0d6317cf48cf0844f8080f8c401a9b800be4 Mon Sep 17 00:00:00 2001
From: Andrii Osipov <aosipov@anaconda.com>
Date: Fri, 31 Jan 2025 15:39:44 -0800
Subject: [PATCH] fix asserts

---
 tests/test_detector_postal_codes.py | 4 ++--
 tests/test_exceptions.py            | 2 +-
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/tests/test_detector_postal_codes.py b/tests/test_detector_postal_codes.py
index 43a19b0..537c18f 100644
--- a/tests/test_detector_postal_codes.py
+++ b/tests/test_detector_postal_codes.py
@@ -57,7 +57,7 @@ class PostalCodesTestCase(unittest.TestCase):
         for postal_code, result in to_test:
             matches = list(detector.iter_filth(test_str.format(postal_code)))
             if result:
-                self.assertEquals(len(matches), 1)
+                self.assertEqual(len(matches), 1)
                 self.assertEquals(matches[0].text, postal_code)
             else:
                 self.assertEquals(matches, [])
@@ -87,5 +87,5 @@ class PostalCodesTestCase(unittest.TestCase):
                     for post_code in post_codes:
                         filth_list = list(detector.iter_filth(post_code))
                         error_message = "Unable to match postcode {} from {}".format(post_code, data_file_name)
-                        self.assertEquals(1, len(filth_list), error_message)
+                        self.assertEqual(1, len(filth_list), error_message)
                         self.assertEquals(post_code, filth_list[0].text)
diff --git a/tests/test_exceptions.py b/tests/test_exceptions.py
index 29f5c70..09b0951 100644
--- a/tests/test_exceptions.py
+++ b/tests/test_exceptions.py
@@ -8,6 +8,6 @@ class ExceptionsTestCase(unittest.TestCase):
         exception = exceptions.ScrubadubException()
         exception.var = 'there'
 
-        self.assertEquals(exception.render('test'), 'test')
+        self.assertEqual(exception.render('test'), 'test')
         self.assertEquals(exception.render('url %(issues_url)s'), 'url ' + exception.issues_url)
         self.assertEquals(exception.render('hello %(var)s'), 'hello there')
-- 
2.39.3 (Apple Git-146)

